[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "groq>=1.6.0",
    "jsom>=0.0.5",
    "passlib[bcrypt]>=1.7.4",
    "python-dotenv>=1.2.3",
    "python-jose[cryptography]>=3.5.0",
    "qdrant-client>=1.19.0",
    "sentence-transformers>=6.0.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
    "youtube-transcript-api>=1.2.4",
]
